import {
  AdministrativeLocation,
  Profile,
  ProfileRole,
  Herd,
  Animal,
  HealthReport,
  CaseAssessment,
  AnimalTreatment,
  AnimalVaccination,
  DiagnosticSample,
  CaseEscalation,
  HealthAdvisory,
  HerdHealthEvent,
  DiseaseCatalogItem,
  HealthReportDisease,
  WeatherObservation,
  RiskAssessment,
  OutbreakEvent,
  AppNotification,
} from '@/types/database';
import { DiseaseAlert } from '@/types/notificationSystem';

export const initialLocations: AdministrativeLocation[] = [
  { id: 'loc-pune', name: 'Pune (पुणे)', name_en: 'Pune', name_hi: 'पुणे', name_mr: 'पुणे', level: 'district', parent_id: null, latitude: 18.5204, longitude: 73.8567 },
  { id: 'loc-shirur', name: 'Shirur (शिरूर)', name_en: 'Shirur', name_hi: 'शिरूर', name_mr: 'शिरूर', level: 'block', parent_id: 'loc-pune', latitude: 18.8256, longitude: 74.3789 },
  { id: 'loc-haveli', name: 'Haveli (हवेली)', name_en: 'Haveli', name_hi: 'हवेली', name_mr: 'हवेली', level: 'block', parent_id: 'loc-pune', latitude: 18.4575, longitude: 73.8677 },
  { id: 'loc-baramati', name: 'Baramati (बारामती)', name_en: 'Baramati', name_hi: 'बारामती', name_mr: 'बारामती', level: 'block', parent_id: 'loc-pune', latitude: 18.1517, longitude: 74.5768 },
  { id: 'loc-khed', name: 'Khed (खेड)', name_en: 'Khed', name_hi: 'खेड', name_mr: 'खेड', level: 'block', parent_id: 'loc-pune', latitude: 18.8500, longitude: 73.9100 },
  { id: 'loc-shirapur', name: 'Shirapur (शिरापूर)', name_en: 'Shirapur', name_hi: 'शिरापूर', name_mr: 'शिरापूर', level: 'village', parent_id: 'loc-shirur', latitude: 18.8120, longitude: 74.3910 },
  { id: 'loc-kavathe', name: 'Kavathe (कवठे)', name_en: 'Kavathe', name_hi: 'कवठे', name_mr: 'कवठे', level: 'village', parent_id: 'loc-shirur', latitude: 18.8450, longitude: 74.3420 },
  { id: 'loc-koregaon', name: 'Koregaon Bhima (कोरेगाव भीमा)', name_en: 'Koregaon Bhima', name_hi: 'कोरेगाव भीमा', name_mr: 'कोरेगाव भीमा', level: 'village', parent_id: 'loc-haveli', latitude: 18.6520, longitude: 74.0710 },
  { id: 'loc-baburdi', name: 'Baburdi (बाबुर्डी)', name_en: 'Baburdi', name_hi: 'बाबुर्डी', name_mr: 'बाबुर्डी', level: 'village', parent_id: 'loc-shirur', latitude: 18.7900, longitude: 74.4200 },
];

export const initialProfiles: Profile[] = [
  { id: 'prof-farmer-1', full_name: 'Suresh Shinde', phone: '+91 98220 12345', location_id: 'loc-shirapur', is_active: true },
  { id: 'prof-field-1', full_name: 'Ramesh Gaikwad', phone: '+91 98220 54321', location_id: 'loc-shirur', is_active: true },
  { id: 'prof-vet-1', full_name: 'Dr. Mahendra Kale', phone: '+91 98220 99887', location_id: 'loc-pune', is_active: true },
  { id: 'prof-govt-1', full_name: 'Dr. Sunita Patil (DAHO)', phone: '+91 98220 66778', location_id: 'loc-pune', is_active: true },
];

export const initialProfileRoles: ProfileRole[] = [
  { profile_id: 'prof-farmer-1', role: 'farmer', assigned_at: '2026-01-10T10:00:00Z' },
  { profile_id: 'prof-field-1', role: 'veterinarian', assigned_at: '2026-01-10T10:00:00Z' },
  { profile_id: 'prof-vet-1', role: 'veterinarian', assigned_at: '2026-01-10T10:00:00Z' },
  { profile_id: 'prof-govt-1', role: 'government', assigned_at: '2026-01-10T10:00:00Z' },
];

export const initialHerds: Herd[] = [
  { id: 'herd-1', owner_profile_id: 'prof-farmer-1', name: 'Shinde Dairy & Livestock Farm', location_id: 'loc-shirapur' },
  { id: 'herd-2', owner_profile_id: 'prof-farmer-1', name: 'Pasture Herd 2', location_id: 'loc-shirapur' },
];

export const initialAnimals: Animal[] = [
  { id: 'anim-1', herd_id: 'herd-1', tag_number: 'COW-023', species: 'Cattle', breed: 'Gir', sex: 'female', date_of_birth: '2022-04-12' },
  { id: 'anim-2', herd_id: 'herd-1', tag_number: 'BUF-015', species: 'Buffalo', breed: 'Murrah', sex: 'female', date_of_birth: '2021-09-20' },
  { id: 'anim-3', herd_id: 'herd-1', tag_number: 'OXN-008', species: 'Cattle', breed: 'Khillari', sex: 'male', date_of_birth: '2020-03-15' },
  { id: 'anim-4', herd_id: 'herd-1', tag_number: 'COW-012', species: 'Cattle', breed: 'Holstein Friesian', sex: 'female', date_of_birth: '2023-01-10' },
  { id: 'anim-5', herd_id: 'herd-1', tag_number: 'COW-045', species: 'Cattle', breed: 'Sahiwal', sex: 'female', date_of_birth: '2022-08-05' },
  { id: 'anim-6', herd_id: 'herd-1', tag_number: 'GOT-009', species: 'Goat', breed: 'Osmanabadi', sex: 'female', date_of_birth: '2023-06-18' },
  { id: 'anim-7', herd_id: 'herd-1', tag_number: 'HRS-007', species: 'Horse', breed: 'Marwari', sex: 'male', date_of_birth: '2021-05-10' },
];

export const initialDiseases: DiseaseCatalogItem[] = [
  {
    id: 'dis-fmd',
    name: 'Foot and Mouth Disease (FMD)',
    name_en: 'Foot and Mouth Disease (FMD)',
    name_hi: 'खुरपका और मुंहपका रोग (FMD)',
    name_mr: 'लाळ-खुरकूत रोग (FMD)',
    description: 'Highly contagious viral disease causing vesicles and blisters on feet, tongue, and teats, severe drop in milk yield.',
    description_en: 'Highly contagious viral disease causing vesicles and blisters on feet, tongue, and teats, severe drop in milk yield.',
    description_hi: 'अत्यधिक संक्रामक वायरल रोग जो पैरों, जीभ और थनों पर छाले और फफोले पैदा करता है, दूध उत्पादन में भारी गिरावट आती है।',
    description_mr: 'अतिशय संसर्गजन्य विषाणूजन्य आजार ज्यामध्ये पाय, जीभ व कासेवर फोड येतात आणि दुग्धोत्पादनात मोठी घट होते.',
    species: 'Cattle, Buffalo, Sheep, Goat',
    severity: 'high',
    is_active: true,
  },
  {
    id: 'dis-lsd',
    name: 'Lumpy Skin Disease (LSD)',
    name_en: 'Lumpy Skin Disease (LSD)',
    name_hi: 'लम्पी त्वचा रोग (LSD)',
    name_mr: 'लम्पी चर्मरोग (LSD)',
    description: 'Poxviral disease characterized by nodular lesions covering skin and mucous membranes, high fever, and edema.',
    description_en: 'Poxviral disease characterized by nodular lesions covering skin and mucous membranes, high fever, and edema.',
    description_hi: 'पॉक्सवायरस जनित रोग जिसमें त्वचा और श्लेष्मा झिल्ली पर गांठदार घाव, तेज बुखार और सूजन होती है।',
    description_mr: 'विषाणूजन्य आजार ज्यामध्ये त्वचेवर गाठी येतात, तीव्र ताप येतो आणि पाय व गळ्याभोवती सूज येते.',
    species: 'Cattle, Buffalo',
    severity: 'high',
    is_active: true,
  },
  {
    id: 'dis-anthrax',
    name: 'Anthrax (Bacillus anthracis)',
    name_en: 'Anthrax (Bacillus anthracis)',
    name_hi: 'एंथ्रेक्स (गिलटी रोग)',
    name_mr: 'अँथ्रॅक्स (काळपुळी)',
    description: 'Severe bacterial zoonotic infection marked by sudden death, unclotted bleeding from body orifices, and high fever.',
    description_en: 'Severe bacterial zoonotic infection marked by sudden death, unclotted bleeding from body orifices, and high fever.',
    description_hi: 'गंभीर जीवाणुजनित संक्रामक रोग जिसमें अचानक मृत्यु, प्राकृतिक छिद्रों से बिना जमा हुआ रक्तस्राव और तेज बुखार होता है।',
    description_mr: 'तीव्र जिवाणूजन्य संसर्ग ज्यामध्ये जनावराचा अचानक मृत्यू होतो आणि शरीराच्या छिद्रांमधून काळे रक्त वाहते.',
    species: 'All Ruminants',
    severity: 'critical',
    is_active: true,
  },
  {
    id: 'dis-brd',
    name: 'Bovine Respiratory Disease (BRD)',
    name_en: 'Bovine Respiratory Disease (BRD)',
    name_hi: 'गोवंशीय श्वसन रोग (BRD)',
    name_mr: 'गुरांचा श्वसन रोग (BRD)',
    description: 'Complex multifactorial respiratory condition with fever, purulent nasal discharge, and acute dyspnea.',
    description_en: 'Complex multifactorial respiratory condition with fever, purulent nasal discharge, and acute dyspnea.',
    description_hi: 'जटिल श्वसन स्थिति जिसमें बुखार, नाक से मवाद जैसा स्राव और सांस लेने में गंभीर कठिनाई होती है।',
    description_mr: 'जनावरांचा श्वसनमार्गाचा संसर्ग ज्यामध्ये खोकला, नाकातून पू येणे व धाप लागणे अशी लक्षणे दिसतात.',
    species: 'Cattle, Buffalo',
    severity: 'medium',
    is_active: true,
  },
  {
    id: 'dis-ppr',
    name: 'Peste des Petits Ruminants (PPR)',
    name_en: 'Peste des Petits Ruminants (PPR)',
    name_hi: 'बकरियों का प्लेग (PPR)',
    name_mr: 'शेळ्या-मेंढ्यांचा प्लेग (PPR)',
    description: 'Viral goat plague with stomatitis, pneumo-enteritis, and high mortality in small ruminants.',
    description_en: 'Viral goat plague with stomatitis, pneumo-enteritis, and high mortality in small ruminants.',
    description_hi: 'बकरियों और भेड़ों का घातक वायरल रोग जिसमें मुंह में छाले, निमोनिया और पतले दस्त होते हैं।',
    description_mr: 'शेळ्या व मेंढ्यांचा प्राणघातक विषाणूजन्य आजार ज्यामध्ये तोंडाला अल्सर, न्यूमोनिया आणि तीव्र हगवण लागते.',
    species: 'Goat, Sheep',
    severity: 'high',
    is_active: true,
  },
  {
    id: 'dis-brucellosis',
    name: 'Brucellosis',
    name_en: 'Brucellosis',
    name_hi: 'ब्रुसेलोसिस (संक्रामक गर्भपात)',
    name_mr: 'ब्रुसेलोसिस (संसर्गजन्य गर्भपात)',
    description: 'Chronic bacterial disease causing late abortions, retained placenta, and reduced fertility.',
    description_en: 'Chronic bacterial disease causing late abortions, retained placenta, and reduced fertility.',
    description_hi: 'पुरानी जीवाणु बीमारी जो गर्भावस्था के अंतिम चरण में गर्भपात और बांझपन का कारण बनती है।',
    description_mr: 'दीर्घकालीन जिवाणू आजार ज्यामुळे शेवटच्या टप्प्यातील गर्भपात, वार अडकणे व वंध्यत्व येते.',
    species: 'Cattle, Buffalo',
    severity: 'medium',
    is_active: true,
  },
];

export const initialHealthReports: HealthReport[] = [
  {
    id: 'rep-mh-2048',
    animal_id: 'anim-1',
    reported_by: 'prof-farmer-1',
    source: 'mobile',
    symptoms: 'Fever, Nasal discharge, Coughing, Reduced milk production',
    mortality_count: 0,
    notes: 'Cow stopped grazing yesterday morning. High temperature recorded by field thermometer. 4 other cows showing mild discharge.',
    reported_at: '2026-09-12T05:30:00Z',
    created_at: '2026-09-12T05:30:00Z',
  },
  {
    id: 'rep-mh-2045',
    animal_id: 'anim-3',
    reported_by: 'prof-farmer-1',
    source: 'mobile',
    symptoms: 'Difficulty breathing, Weakness, Sudden death',
    mortality_count: 1,
    notes: 'Sudden collapse in pen 2. Neighboring farm in Shirapur reported 1 death 48 hours ago.',
    reported_at: '2026-09-11T14:15:00Z',
    created_at: '2026-09-11T14:15:00Z',
  },
  {
    id: 'rep-mh-2039',
    animal_id: 'anim-6',
    reported_by: 'prof-field-1',
    source: 'web',
    symptoms: 'Diarrhea, Weakness, Loss of appetite',
    mortality_count: 0,
    notes: 'Goat flock grazing near river bed showing watery diarrhea.',
    reported_at: '2026-09-10T09:00:00Z',
    created_at: '2026-09-10T09:00:00Z',
  },
  {
    id: 'rep-mh-2044',
    animal_id: 'anim-2',
    reported_by: 'prof-farmer-1',
    source: 'ivr',
    symptoms: 'Reduced milk production, Loss of appetite',
    mortality_count: 0,
    notes: 'Reported via toll-free IVR line. Milk yield dropped from 12L to 4L.',
    reported_at: '2026-09-11T18:00:00Z',
    created_at: '2026-09-11T18:00:00Z',
  },
];

export const initialCaseAssessments: CaseAssessment[] = [
  {
    id: 'assess-1',
    health_report_id: 'rep-mh-2048',
    status: 'probable',
    triage_method: 'ai_assisted',
    assessment_notes: 'Symptoms match Bovine Respiratory Disease / early FMD cluster. High transmission probability due to communal watering.',
    assessed_by: 'prof-vet-1',
    assessed_at: '2026-09-12T05:45:00Z',
  },
  {
    id: 'assess-2',
    health_report_id: 'rep-mh-2045',
    status: 'suspected',
    triage_method: 'rule_based',
    assessment_notes: 'Sudden death flag triggered. Immediate biosafety precautions required. Rule out Anthrax / Hemorrhagic Septicemia.',
    assessed_by: 'prof-vet-1',
    assessed_at: '2026-09-11T14:30:00Z',
  },
  {
    id: 'assess-3',
    health_report_id: 'rep-mh-2039',
    status: 'suspected',
    triage_method: 'manual',
    assessment_notes: 'Parasitic enteritis or early PPR. Hydration therapy prescribed.',
    assessed_by: 'prof-field-1',
    assessed_at: '2026-09-10T10:00:00Z',
  },
];

export const initialHealthReportDiseases: HealthReportDisease[] = [
  { id: 'hrd-1', health_report_id: 'rep-mh-2048', disease_id: 'dis-brd', is_primary: true, confidence: 84, notes: 'Respiratory cluster pattern matches' },
  { id: 'hrd-2', health_report_id: 'rep-mh-2048', disease_id: 'dis-fmd', is_primary: false, confidence: 45, notes: 'Secondary differential' },
  { id: 'hrd-3', health_report_id: 'rep-mh-2045', disease_id: 'dis-anthrax', is_primary: true, confidence: 78, notes: 'Sudden death trigger' },
];

export const initialRiskAssessments: RiskAssessment[] = [
  {
    id: 'risk-1',
    health_report_id: 'rep-mh-2048',
    location_id: 'loc-shirapur',
    risk_level: 'high',
    risk_score: 82,
    assessment_method: 'ai_assisted',
    reasoning: 'Multiple animals affected within 48h in Shirapur. High humidity and standing water accelerating vector and bacterial transmission.',
    assessed_by: 'prof-vet-1',
    assessed_at: '2026-09-12T05:50:00Z',
  },
  {
    id: 'risk-2',
    health_report_id: null,
    location_id: 'loc-shirur',
    risk_level: 'critical',
    risk_score: 91,
    assessment_method: 'ai_assisted',
    reasoning: 'Cluster of 14 cases across Shirur block within 5km radius.',
    assessed_by: 'prof-govt-1',
    assessed_at: '2026-09-11T12:00:00Z',
  },
];

export const initialDiagnosticSamples: DiagnosticSample[] = [
  {
    id: 'samp-1',
    health_report_id: 'rep-mh-2048',
    sample_type: 'Nasal swab',
    collected_at: '2026-09-12T06:00:00Z',
    sent_at: '2026-09-12T07:15:00Z',
    received_at: '2026-09-12T09:30:00Z',
    tested_at: null,
    status: 'received',
    result: null,
    notes: 'Sample received at District Veterinary Lab Pune. Testing for respiratory panel in progress.',
  },
];

export const initialCaseEscalations: CaseEscalation[] = [
  {
    id: 'esc-1',
    health_report_id: 'rep-mh-2045',
    escalated_to: 'Dr. Sunita Patil (DAHO)',
    reason: 'Sudden mortality event with rapid progression in Shirur block.',
    status: 'in_progress',
    created_at: '2026-09-11T15:00:00Z',
    resolved_at: null,
  },
];

export const initialTreatments: AnimalTreatment[] = [
  {
    id: 'treat-1',
    animal_id: 'anim-1',
    prescribed_by: 'prof-vet-1',
    treatment_name: 'Ceftiofur Sodium (Antibiotic course)',
    dosage: '10ml IM daily for 3 days',
    treatment_date: '2026-09-12',
    notes: 'Isolate animal and ensure fresh hydration.',
  },
];

export const initialVaccinations: AnimalVaccination[] = [
  {
    id: 'vac-1',
    animal_id: 'anim-1',
    vaccine_name: 'FMD Quadrivalent Vaccine',
    vaccination_date: '2025-11-10',
    next_due_date: '2026-09-16',
    administered_by: 'prof-vet-1',
    notes: 'Routine bi-annual vaccination booster due.',
  },
  {
    id: 'vac-2',
    animal_id: 'anim-2',
    vaccine_name: 'Haemorrhagic Septicaemia (HS) Vaccine',
    vaccination_date: '2025-10-15',
    next_due_date: '2026-10-15',
    administered_by: 'prof-vet-1',
    notes: 'Annual booster dose.',
  },
];

export const initialHerdHealthEvents: HerdHealthEvent[] = [
  {
    id: 'hhe-1',
    herd_id: 'herd-1',
    reported_by: 'prof-farmer-1',
    event_type: 'respiratory_outbreak',
    affected_count: 5,
    mortality_count: 0,
    description: 'Sudden nasal discharge and coughing across 5 animals in Shed B.',
    event_date: '2026-09-11',
    created_at: '2026-09-11T10:00:00Z',
  },
  {
    id: 'hhe-2',
    herd_id: 'herd-2',
    reported_by: 'prof-farmer-2',
    event_type: 'sudden_mortality',
    affected_count: 3,
    mortality_count: 1,
    description: 'Unusual lethargy and sudden death of 1 calf within 12 hours.',
    event_date: '2026-09-10',
    created_at: '2026-09-10T14:30:00Z',
  },
];

export const initialWeather: WeatherObservation[] = [
  {
    id: 'wx-1',
    location_id: 'loc-shirur',
    observed_at: '2026-09-12T06:00:00Z',
    temperature_c: 28.4,
    humidity_percent: 86,
    rainfall_mm: 34.2,
    wind_speed_kmh: 14.5,
    description: 'Heavy seasonal monsoon showers with waterlogging in low-lying pastures.',
    description_en: 'Heavy seasonal monsoon showers with waterlogging in low-lying pastures.',
    description_hi: 'भारी मानसूनी बारिश और निचले चारागाहों में जलभराव।',
    description_mr: 'मुसळधार मान्सून पाऊस आणि सखल भागातील चराऊ कुरणात पाणी साचले आहे.',
  },
  {
    id: 'wx-2',
    location_id: 'loc-baramati',
    observed_at: '2026-09-12T06:00:00Z',
    temperature_c: 29.1,
    humidity_percent: 78,
    rainfall_mm: 12.0,
    wind_speed_kmh: 11.2,
    description: 'Partly cloudy with scattered rain.',
    description_en: 'Partly cloudy with scattered rain.',
    description_hi: 'आंशिक रूप से बादल छाए रहेंगे और छिटपुट बारिश होगी।',
    description_mr: 'अंशतः ढगाळ वातावरण आणि तुरळक पावसाची शक्यता.',
  },
];

export const initialOutbreaks: OutbreakEvent[] = [
  {
    id: 'out-1',
    disease_id: 'dis-fmd',
    location_id: 'loc-shirur',
    title: 'Foot and Mouth Disease Cluster - Shirur Block',
    title_en: 'Foot and Mouth Disease Cluster - Shirur Block',
    title_hi: 'खुरपका और मुंहपका रोग प्रकोप - शिरूर तालुका',
    title_mr: 'लाळ-खुरकूत रोग उद्रेक - शिरूर तालुका',
    description: 'Unusual incidence of blisters and reduced lactation across 11 dairy farms along Shirur-Koregaon corridor.',
    description_en: 'Unusual incidence of blisters and reduced lactation across 11 dairy farms along Shirur-Koregaon corridor.',
    description_hi: 'शिरूर-कोरेगाव गलियारे में 11 डेयरी फार्मों में छालों और दूध उत्पादन में कमी की असामान्य घटनाएं।',
    description_mr: 'शिरूर-कोरेगाव पट्ट्यातील ११ गोठ्यांमध्ये जनावरांना फोड व दुग्धोत्पादनात घट झाल्याची नोंद.',
    severity: 'critical',
    affected_herds: 11,
    affected_animals: 47,
    mortality_count: 3,
    started_at: '2026-09-08T00:00:00Z',
    ended_at: null,
    status: 'active',
    created_by: 'prof-govt-1',
  },
  {
    id: 'out-2',
    disease_id: 'dis-lsd',
    location_id: 'loc-baramati',
    title: 'Suspected Lumpy Skin Disease Surveillance',
    title_en: 'Suspected Lumpy Skin Disease Surveillance',
    title_hi: 'संभावित लम्पी त्वचा रोग निगरानी - बारामती',
    title_mr: 'संशयित लम्पी चर्मरोग पाळत व सर्वेक्षण - बारामती',
    description: 'Nodular skin lesions detected in 5 farms. Vector control operations activated.',
    description_en: 'Nodular skin lesions detected in 5 farms. Vector control operations activated.',
    description_hi: '5 फार्मों में त्वचा पर गांठें देखी गईं। कीट नियंत्रण अभियान शुरू किया गया है।',
    description_mr: '५ गोठ्यांमध्ये त्वचेवर गाठी आढळल्या. डास-माशा प्रतिबंधक औषध फवारणी मोहीम सुरू केली आहे.',
    severity: 'medium',
    affected_herds: 5,
    affected_animals: 14,
    mortality_count: 0,
    started_at: '2026-09-05T00:00:00Z',
    ended_at: null,
    status: 'contained',
    created_by: 'prof-govt-1',
  },
];

export const initialAdvisories: HealthAdvisory[] = [
  {
    id: 'adv-1-en',
    health_report_id: null,
    title: 'Monsoon Pasture Alert: High Risk of Vector and Foot Infections',
    message: 'Continuous rainfall has elevated humidity above 85%. Keep animal sheds dry with dry straw bedding. Clean feeding troughs daily and avoid grazing in stagnant water pools.',
    language: 'en',
    created_by: 'prof-vet-1',
    created_at: '2026-09-11T08:00:00Z',
  },
  {
    id: 'adv-1-hi',
    health_report_id: null,
    title: 'मानसून चारागाह चेतावनी: संक्रमण और खुरपका का उच्च जोखिम',
    message: 'लगातार बारिश के कारण नमी 85% से अधिक हो गई है। पशु बाड़े को सूखा रखें। पीने का पानी साफ दें और जलभराव वाले क्षेत्रों में पशुओं को चरने न भेजें।',
    language: 'hi',
    created_by: 'prof-vet-1',
    created_at: '2026-09-11T08:00:00Z',
  },
  {
    id: 'adv-1-mr',
    health_report_id: null,
    title: 'पावसाळी चारा व गोठा दक्षता: जंतुसंसर्ग व लाळ-खुरकूतचा वाढता धोका',
    message: 'सततच्या पावसामुळे गोठ्यात दमटपणा वाढला आहे. गोठ्याची जमीन कोरडी ठेवा, जंतुनाशक चुन्याची भुकटी टाका. दूषित किंवा साचलेले पाणी पिण्यास देऊ नका. ताप आल्यास तात्काळ पशुवैद्यकांशी संपर्क साधा.',
    language: 'mr',
    created_by: 'prof-vet-1',
    created_at: '2026-09-11T08:00:00Z',
  },
  {
    id: 'adv-2-en',
    health_report_id: null,
    title: 'FMD Ring Vaccination Protocol Activated in 5km Radius',
    message: 'Mandatory ring vaccination in progress for all cattle and buffaloes in Shirur and adjoining blocks. Isolate newly purchased cattle for 14 days.',
    language: 'en',
    created_by: 'prof-govt-1',
    created_at: '2026-09-10T11:00:00Z',
  },
  {
    id: 'adv-2-hi',
    health_report_id: null,
    title: '5 किमी के दायरे में खुरपका-मुंहपका रिंग टीकाकरण प्रोटोकॉल सक्रिय',
    message: 'शिरूर और आसपास के ब्लॉकों में सभी मवेशियों और भैंसों के लिए रिंग टीकाकरण जारी है। नए खरीदे गए पशुओं को 14 दिनों तक अलग रखें।',
    language: 'hi',
    created_by: 'prof-govt-1',
    created_at: '2026-09-10T11:00:00Z',
  },
  {
    id: 'adv-2-mr',
    health_report_id: null,
    title: '५ किमी परिसरात लाळ-खुरकूत रिंग लसीकरण मोहीम सुरू',
    message: 'शिरूर व लगतच्या गावांमध्ये सर्व गायी व म्हशींचे रिंग लसीकरण सुरू आहे. नवीन आणलेली जनावरे १४ दिवस गोठ्यापासून वेगळी ठेवा.',
    language: 'mr',
    created_by: 'prof-govt-1',
    created_at: '2026-09-10T11:00:00Z',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    recipient_profile_id: 'prof-farmer-1',
    health_report_id: 'rep-mh-2048',
    outbreak_event_id: 'out-1',
    title: 'Possible Disease Cluster Detected in Shirur',
    title_en: 'Possible Disease Cluster Detected in Shirur',
    title_hi: 'शिरूर में संभावित बीमारी का प्रकोप दर्ज',
    title_mr: 'शिरूर तालुक्यात संशयित रोगाचा प्रादुर्भाव आढळला',
    message: 'Similar respiratory & fever symptoms reported within 5 km of your village. Monitor your animals closely.',
    message_en: 'Similar respiratory & fever symptoms reported within 5 km of your village. Monitor your animals closely.',
    message_hi: 'आपके गांव के 5 किमी के भीतर समान श्वसन और बुखार के लक्षण सामने आए हैं। अपने पशुओं की कड़ी निगरानी रखें।',
    message_mr: 'आपल्या गावाच्या ५ किमी परिसरात ताप व श्वसनाच्या लक्षणांची नोंद झाली आहे. जनावरांचे काळजीपूर्वक निरीक्षण करा.',
    notification_type: 'outbreak_alert',
    is_read: false,
    created_at: '2026-09-12T06:15:00Z',
    read_at: null,
  },
  {
    id: 'notif-2',
    recipient_profile_id: 'prof-farmer-1',
    health_report_id: null,
    outbreak_event_id: null,
    title: 'Vaccination Due: FMD Booster in 4 Days',
    title_en: 'Vaccination Due: FMD Booster in 4 Days',
    title_hi: 'टीकाकरण देय: FMD बूस्टर 4 दिनों में',
    title_mr: 'लसीकरण बाकी: लाळ-खुरकूत बूस्टर लस ४ दिवसांत',
    message: 'COW-023 is scheduled for its bi-annual Foot and Mouth Disease vaccination.',
    message_en: 'COW-023 is scheduled for its bi-annual Foot and Mouth Disease vaccination.',
    message_hi: 'COW-023 के लिए द्विवार्षिक खुरपका-मुंहपका रोग टीकाकरण निर्धारित है।',
    message_mr: 'COW-023 या गायीचे द्विवार्षिक लाळ-खुरकूत लसीकरण नियोजित आहे.',
    notification_type: 'health_alert',
    is_read: false,
    created_at: '2026-09-12T07:00:00Z',
    read_at: null,
  },
  {
    id: 'notif-3',
    recipient_profile_id: 'prof-farmer-1',
    health_report_id: 'rep-mh-2048',
    outbreak_event_id: null,
    title: 'New Urgent Report in Shirapur (#MH-2048)',
    title_en: 'New Urgent Report in Shirapur (#MH-2048)',
    title_hi: 'शिरापूर में नई जरूरी रिपोर्ट (#MH-2048)',
    title_mr: 'शिरापूर गावात नवीन तातडीची केस (#MH-2048)',
    message: 'Farmer Suresh Shinde reported 5 animals affected with fever and discharge. Triage assessment: Probable BRD.',
    message_en: 'Farmer Suresh Shinde reported 5 animals affected with fever and discharge. Triage assessment: Probable BRD.',
    message_hi: 'किसान सुरेश शिंदे ने बुखार और स्राव से प्रभावित 5 पशुओं की रिपोर्ट दर्ज की। प्राथमिक जांच: संभावित BRD।',
    message_mr: 'शेतकरी सुरेश शिंदे यांनी ५ जनावरांना ताप व स्त्राव असल्याची तक्रार नोंदवली. प्राथमिक निदान: संशयित BRD.',
    notification_type: 'escalation',
    is_read: false,
    created_at: '2026-09-12T05:35:00Z',
    read_at: null,
  },
];

export const initialDiseaseAlerts: DiseaseAlert[] = [
  {
    id: 'alert-seed-1',
    disease_id: 'dis-1',
    disease_name: 'Foot and Mouth Disease (FMD)',
    region_level: 'block',
    district: 'Pune',
    block: 'Shirur',
    village: 'Shirapur',
    risk_level: 'high',
    case_count: 6,
    reported_date: '2026-09-10T08:00:00Z',
    alert_start_date: '2026-09-10T08:00:00Z',
    alert_expiry_date: '2026-09-24T23:59:59Z',
    recommended_action: 'Immediate isolation of affected animals, antiseptic foot baths with 4% sodium carbonate, and mandatory ring vaccination within 5km zone.',
    description: 'Cluster of cattle showing vesicular lesions on tongue and interdigital spaces reported in Shirur block.',
    containment_radius_km: 5,
    species_targeted: ['Cattle', 'Buffalo'],
    preventive_measures: [
      'Isolate affected livestock immediately',
      'Disinfect premise with 4% sodium carbonate solution',
      'Do not transport animals across village or block boundaries',
    ],
    source_authority: 'District Animal Husbandry Office (DAHO), Pune',
    status: 'active',
    target_audience: 'both',
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'alert-seed-2',
    disease_id: 'dis-2',
    disease_name: 'Lumpy Skin Disease (LSD)',
    region_level: 'district',
    district: 'Pune',
    block: 'Baramati',
    risk_level: 'moderate',
    case_count: 4,
    reported_date: '2026-09-08T10:00:00Z',
    alert_start_date: '2026-09-08T10:00:00Z',
    alert_expiry_date: '2026-09-22T23:59:59Z',
    recommended_action: 'Strict vector control with insect repellents, mosquito netting, and immediate goat pox vaccine booster administration.',
    description: 'Nodular skin eruptions detected across dairy farms in Baramati sector.',
    containment_radius_km: 10,
    species_targeted: ['Cattle'],
    preventive_measures: [
      'Vector control against biting flies and mosquitoes',
      'Daily body temperature checks',
      'Administer supportive antipyretic therapy',
    ],
    source_authority: 'State Veterinary Disease Diagnostic Laboratory (VDL), Pune',
    status: 'active',
    target_audience: 'both',
    created_at: '2026-09-08T10:00:00Z',
  },
];
